name: docker build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: login docker
      run: echo ${{ secrets.CCR_PASSWORD }} | docker login -u ${{ secrets.CCR_USERNAME }} --password-stdin ccr.ccs.tencentyun.com
    - name: docker register
      run: docker info
    - name: Build the Docker image
      run: docker build -t wajika/geektime:latest .
    - name: docker push
      run: docker push wajika/geektime:latest
